#!/usr/bin/env python3
"""Keep Localizable.strings in sync with the Swift sources.

The Swift compiler extracts every localisable literal (SwiftUI LocalizedStringKey
and String(localized:)) with -emit-localized-strings. This script:
  extract  - rebuild with extraction and write en.lproj/Localizable.strings
  check    - fail if a language misses keys or has obsolete ones (used by CI)
Usage: scripts/localization.py extract|check
"""
import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "app"
RES = APP / "Resources"
LANGS = ["it"]


def sdk_env():
    env = dict(os.environ)
    sdk = os.environ.get("IRUFUS_SDK")
    if sdk:
        env["SDKROOT"] = sdk
    return env


def extract_keys():
    build = pathlib.Path(tempfile.mkdtemp(prefix="irufus-loc-"))
    out = build / "strings"
    out.mkdir()
    subprocess.run(
        ["swift", "build", "--package-path", str(APP), "--build-path", str(build / "b"),
         "-Xswiftc", "-emit-localized-strings", "-Xswiftc", "-emit-localized-strings-path", "-Xswiftc", str(out)],
        check=True, env=sdk_env(), stdout=subprocess.DEVNULL)
    keys = {}
    # Where the .stringsdata files land depends on the build system (flat in `out` with the
    # native one, under the target's build folder with swiftbuild): filter on the source path.
    for f in build.rglob("*.stringsdata"):
        data = json.loads(f.read_text())
        source = pathlib.Path(data.get("source", ""))
        if source.parent.name != "iRufus":
            continue
        for entry in data.get("tables", {}).get("Localizable", []):
            keys.setdefault(entry["key"], f"{source.name}:{entry['location']['startingLine']}")
    return keys


def escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def parse_strings(path):
    text = path.read_text(encoding="utf-8")
    pairs = re.findall(r'^"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)";', text, re.M)
    unesc = lambda s: s.replace("\\n", "\n").replace('\\"', '"').replace("\\\\", "\\")
    return {unesc(k): unesc(v) for k, v in pairs}


def write_en(keys):
    d = RES / "en.lproj"
    d.mkdir(parents=True, exist_ok=True)
    lines = ["/* Generated by scripts/localization.py extract — English source strings. */", ""]
    for k in sorted(keys):
        lines.append(f'/* {keys[k]} */')
        lines.append(f'"{escape(k)}" = "{escape(k)}";')
    (d / "Localizable.strings").write_text("\n".join(lines) + "\n", encoding="utf-8")


def placeholders(s):
    return sorted(re.findall(r"%(?:\d+\$)?(?:lld|llu|ld|lu|d|u|lf|f|@)", s))


def check(keys):
    ok = True
    for lang in LANGS:
        path = RES / f"{lang}.lproj" / "Localizable.strings"
        have = parse_strings(path) if path.exists() else {}
        missing = sorted(set(keys) - set(have))
        obsolete = sorted(set(have) - set(keys))
        bad = [k for k in keys if k in have and placeholders(k) != placeholders(have[k])]
        for k in missing:
            print(f"[{lang}] missing: {k!r} ({keys[k]})")
        for k in obsolete:
            print(f"[{lang}] obsolete: {k!r}")
        for k in bad:
            print(f"[{lang}] placeholder mismatch: {k!r} -> {have[k]!r}")
        ok &= not missing and not obsolete and not bad
    return ok


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    keys = extract_keys()
    if cmd == "extract":
        write_en(keys)
        print(f"{len(keys)} keys written to en.lproj")
        check(keys)
    elif cmd == "dump":
        print(json.dumps(sorted(keys), ensure_ascii=False, indent=1))
    else:
        sys.exit(0 if check(keys) else 1)
