name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: brew install wimlib
      - run: scripts/ci.sh
